plugins {
    id 'java'
}

group = 'net.lstonstudios'
version = '1.0.0'

tasks.withType(JavaCompile).configureEach {
    options.release.set(17)
}

dependencies {
    compileOnly files('../bungee/bungee.jar', '../bungee/plugins/EaglerXServer.jar')
}

jar {
    archiveBaseName = 'EaglerNotifications'
}